# Welcome to Jekyll!

# Website settings
title: "David's Blog"
description: "David（林伟伟）的Github博客，关于web前端技术领域."
keywords: "David，林伟伟，博客，前端，angularJs，HTML，CSS，javaScript"
baseurl: "/"
url: "http://linweiwei123.github.io"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'http://linweiwei123.github.io/static/img/blog'

# author
author:
  name: 'David'
  first_name: 'Lin'
  last_name: 'David'
  email: 'yitalalww@gmail.com'
  facebook_username: 'yitalalww'
  github_username: 'linweiwei123'
  head_img: 'static/img/landing/linweiwei2.jpg'

# social link
jingyu:
  first_name: 'David'
  last_name: 'Lin'
  description: 'Front-End engineer.'
  link: 'http://linweiwei123.github.io'
  email: 'yitalalww@gmail.com'

# landing page
landing:
  home: '首页'
  projects: '我的项目'
  blog: '博客'
  about: '关于我'
  career: '职业'
  skills: '技术栈'
  link: '友情链接'

# my projects
project:
  saplatform:
    name: 'Saplatform'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/css.png'
  jalpc:
    name: 'Jalpc'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.png'
  angularjs:
    name: 'Jalpc-A'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.png'
  Rsser:
    name: 'Rsser'
    url: '/Jack614/Rsser'
    img: 'static/img/landing/rsser.png'

# blog index
index:
  home: '主页'
  python: 'CSS3'
  linux: 'AngularJs'
  html: 'HTML5'
  database: 'MEAN'
  mac: '前端高级进阶'
  life: '前端架构'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
